### ISSUE TITLE
What happen with the theme!!

### ISSUE THREAD

**Issue by dpshelio** [OpenAstronomy/Universe_OA#21]
The theme has changed and nothing looks like it used to!! Why????!!!!!
And then @Cadair prefers nikola.... :stuck_out_tongue_closed_eyes:

**Comment by Cadair** [comment]
The bump to Nikola 4.0 did change a few things, the quickest fix might be to pin to 3.x. I did a bunch of fixes to the pyastro site for Nikola 4.0: https://github.com/OpenAstronomy/pyastro/commit/f9f192db20dc8c4ecf2f929e4a7c5d20f8f368e8

I can have a look at this if you want me to.

**Comment by dpshelio** [comment]
Solved with a89fbc8c40fc41e04f117a4bbb40b127219739c1 and similar on `run`. It only required to fix a blog post from a student last year and update the theme to `bootstrap4`. I've also updated the other things for the new nikola. Thanks @Cadair
