### ISSUE TITLE
Bad Student URL

### ISSUE THREAD

**Issue by mileslucas** [OpenAstronomy/Universe_OA#52]
@siddharthlal25 blog link in the top banner is currently routing to a 404, since his blog is at https://siddharthlal25.github.io/blog/ but the [regex parser](https://github.com/OpenAstronomy/Universe_OA/blob/f86cd4c0ae97e0c4d9138eeb2dca2465ce696efb/plugins/sidebar/sidebar.py#L34) fails to parse past the first `/`, resulting in https://siddharthlal25.github.io for the URl. 
If you change the `regex_url` to be `"(?P<url>https?://[^\s/]+(/[^s/]+/)?)"` the behavior changes to
```
"https://siddharthlal25.github.io/blog/gsoc/gsoc-blog-0" => "https://siddharthlal25.github.io/blog/"
"https://siddharthlal25.github.io/blog/fake-page" => "https://siddharthlal25.github.io/blog/"
"https://siddharthlal25.github.io/fake-page" => "https://siddharthlal25.github.io"
```

I don't know if this works with the other students' setups. If its a bigger hassle to change this, perhaps @siddharthlal25 you should add a redirect to your site.

**Comment by dpshelio** [comment]
Thanks @mileslucas - I couldn't use your regex because affected some other posts. Since `/blog/` is quite common for people hosting them on GitHub, I've gone through the easier path, hardcoding that.
