### ISSUE TITLE
BUG: Names aren't picked up properly for blog

### ISSUE THREAD

**Issue by bsipocz** [OpenAstronomy/Universe_OA#71]
IMO the names should be e.g. github handles, or actual names, yet we see e.g. an OpenAstronomy

<img width="616" alt="Screenshot 2022-08-23 at 17 23 19" src="https://user-images.githubusercontent.com/6788290/186288433-9c03b35b-75dc-4964-a8ca-ad040809c14e.png">

**Comment by dpshelio** [comment]
At the moment the author names are taken from the posts, as whatever they name themselves. We could use the github handles as we do to track their contributions, we would need to store that in the posts when they are downloaded.
Probably setting this https://github.com/OpenAstronomy/Universe_OA/blob/fc5d1cd1d448c69bf449b226592fcab87e2cea24/grab.py#L95
to `student`.

**Comment by peopleofnita** [comment]
Is this issue still open? I am new to open-source contribution and I can help with this if this is open

**Comment by jgyasu** [comment]
Is this issue still open? I am new to open-source contribution and I'd like to contribute and learn if this is open

**Comment by bsipocz** [comment]
I suspect this is still and issue, but currently the box is fully gone from the page, but that maybe due to us being in a transition as we started the new gsoc programme but don't yet know who the contributors will be.

**Comment by jgyasu** [comment]
Thanks for the reply, do you think there are more beginner-friendly issues in this project that needs help? I am not applying for the Gsoc, I just found about this project on their page and thought it's cool

**Comment by bsipocz** [comment]
Thanks for the interest!

I expect we'll identify a few issues next week when we populate the page with the new gsoc participants (they will be announced on the 30th).

Otherwise, there are plenty of other front-end issues in the main webpage's repo, I expect most of those are still a problem: https://github.com/OpenAstronomy/openastronomy.github.io/issues
